# Generated by Django 3.0.7 on 2020-07-06 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caro', '0002_auto_20200704_1410'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='count_ready',
            field=models.IntegerField(default=0),
        ),
    ]
