# Generated by Django 3.0.5 on 2020-07-06 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='rank',
            field=models.PositiveIntegerField(default='0'),
        ),
    ]
