<<<<<<< HEAD
# Generated by Django 3.0.5 on 2020-07-07 10:56
=======
# Generated by Django 3.0.5 on 2020-07-06 09:12
>>>>>>> f46710c57e80d885c78287a3f54b0613026efe47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='default.jpg', upload_to='profile_pics')),
<<<<<<< HEAD
                ('rank', models.PositiveIntegerField(default='0')),
                ('wins', models.PositiveIntegerField(default='0')),
                ('loses', models.PositiveIntegerField(default='0')),
=======
>>>>>>> f46710c57e80d885c78287a3f54b0613026efe47
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
