# Generated by Django 3.0.5 on 2020-07-07 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_rank'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='loses',
            field=models.PositiveIntegerField(default='0'),
        ),
        migrations.AddField(
            model_name='profile',
            name='wins',
            field=models.PositiveIntegerField(default='0'),
        ),
    ]
