(function(){var a="undefined"!==typeof window&&"undefined"!==typeof window.document?window.document:{},c="undefined"!==typeof module&&module.exports,d="undefined"!==typeof Element&&"ALLOW_KEYBOARD_INPUT"in Element,b=function(){for(var b,c=["requestFullscreen exitFullscreen fullscreenElement fullscreenEnabled fullscreenchange fullscreenerror".split(" "),"webkitRequestFullscreen webkitExitFullscreen webkitFullscreenElement webkitFullscreenEnabled webkitfullscreenchange webkitfullscreenerror".split(" "),
"webkitRequestFullScreen webkitCancelFullScreen webkitCurrentFullScreenElement webkitCancelFullScreen webkitfullscreenchange webkitfullscreenerror".split(" "),"mozRequestFullScreen mozCancelFullScreen mozFullScreenElement mozFullScreenEnabled mozfullscreenchange mozfullscreenerror".split(" "),"msRequestFullscreen msExitFullscreen msFullscreenElement msFullscreenEnabled MSFullscreenChange MSFullscreenError".split(" ")],e=0,f=c.length,d={};e<f;e++)if((b=c[e])&&b[1]in a){for(e=0;e<b.length;e++)d[c[0][e]]=
b[e];return d}return!1}(),f={change:b.fullscreenchange,error:b.fullscreenerror},h={request:function(c){var f=b.requestFullscreen;c=c||a.documentElement;if(/5\.1[.\d]* Safari/.test(navigator.userAgent))c[f]();else c[f](d&&Element.ALLOW_KEYBOARD_INPUT)},exit:function(){a[b.exitFullscreen]()},toggle:function(a){this.isFullscreen?this.exit():this.request(a)},onchange:function(a){this.on("change",a)},onerror:function(a){this.on("error",a)},on:function(b,c){var e=f[b];e&&a.addEventListener(e,c,!1)},off:function(b,
c){var e=f[b];e&&a.removeEventListener(e,c,!1)},raw:b};b?(Object.defineProperties(h,{isFullscreen:{get:function(){return!!a[b.fullscreenElement]}},element:{enumerable:!0,get:function(){return a[b.fullscreenElement]}},enabled:{enumerable:!0,get:function(){return!!a[b.fullscreenEnabled]}}}),c?module.exports=h:window.screenfull=h):c?module.exports=!1:window.screenfull=!1})();var s_iScaleFactor=1,s_oCanvasLeft,s_oCanvasTop,s_bIsIphone=!1;
(function(a){(jQuery.browser=jQuery.browser||{}).mobile=/android|avantgo|bada\/|blackberry|blazer|compal|elaine|fennec|hiptop|iemobile|ip(ad|hone|od)|iris|kindle|lge |maemo|midp|mmp|netfront|opera m(ob|in)i|palm( os)?|phone|p(ixi|re)\/|plucker|pocket|psp|symbian|tablet|treo|up\.(browser|link)|vodafone|wap|webos|windows (ce|phone)|xda|xiino/i.test(a)||/1207|6310|6590|3gso|4thp|50[1-6]i|770s|802s|a wa|abac|ac(er|oo|s\-)|ai(ko|rn)|al(av|ca|co)|amoi|an(ex|ny|yw)|aptu|ar(ch|go)|as(te|us)|attw|au(di|\-m|r |s )|avan|be(ck|ll|nq)|bi(lb|rd)|bl(ac|az)|br(e|v)w|bumb|bw\-(n|u)|c55\/|capi|ccwa|cdm\-|cell|chtm|cldc|cmd\-|co(mp|nd)|craw|da(it|ll|ng)|dbte|dc\-s|devi|dica|dmob|do(c|p)o|ds(12|\-d)|el(49|ai)|em(l2|ul)|er(ic|k0)|esl8|ez([4-7]0|os|wa|ze)|fetc|fly(\-|_)|g1 u|g560|gene|gf\-5|g\-mo|go(\.w|od)|gr(ad|un)|haie|hcit|hd\-(m|p|t)|hei\-|hi(pt|ta)|hp( i|ip)|hs\-c|ht(c(\-| |_|a|g|p|s|t)|tp)|hu(aw|tc)|i\-(20|go|ma)|i230|iac( |\-|\/)|ibro|idea|ig01|ikom|im1k|inno|ipaq|iris|ja(t|v)a|jbro|jemu|jigs|kddi|keji|kgt( |\/)|klon|kpt |kwc\-|kyo(c|k)|le(no|xi)|lg( g|\/(k|l|u)|50|54|e\-|e\/|\-[a-w])|libw|lynx|m1\-w|m3ga|m50\/|ma(te|ui|xo)|mc(01|21|ca)|m\-cr|me(di|rc|ri)|mi(o8|oa|ts)|mmef|mo(01|02|bi|de|do|t(\-| |o|v)|zz)|mt(50|p1|v )|mwbp|mywa|n10[0-2]|n20[2-3]|n30(0|2)|n50(0|2|5)|n7(0(0|1)|10)|ne((c|m)\-|on|tf|wf|wg|wt)|nok(6|i)|nzph|o2im|op(ti|wv)|oran|owg1|p800|pan(a|d|t)|pdxg|pg(13|\-([1-8]|c))|phil|pire|pl(ay|uc)|pn\-2|po(ck|rt|se)|prox|psio|pt\-g|qa\-a|qc(07|12|21|32|60|\-[2-7]|i\-)|qtek|r380|r600|raks|rim9|ro(ve|zo)|s55\/|sa(ge|ma|mm|ms|ny|va)|sc(01|h\-|oo|p\-)|sdk\/|se(c(\-|0|1)|47|mc|nd|ri)|sgh\-|shar|sie(\-|m)|sk\-0|sl(45|id)|sm(al|ar|b3|it|t5)|so(ft|ny)|sp(01|h\-|v\-|v )|sy(01|mb)|t2(18|50)|t6(00|10|18)|ta(gt|lk)|tcl\-|tdg\-|tel(i|m)|tim\-|t\-mo|to(pl|sh)|ts(70|m\-|m3|m5)|tx\-9|up(\.b|g1|si)|utst|v400|v750|veri|vi(rg|te)|vk(40|5[0-3]|\-v)|vm40|voda|vulc|vx(52|53|60|61|70|80|81|83|85|98)|w3c(\-| )|webc|whit|wi(g |nc|nw)|wmlb|wonu|x700|xda(\-|2|g)|yas\-|your|zeto|zte\-/i.test(a.substr(0,
4))})(navigator.userAgent||navigator.vendor||window.opera);$(window).resize(function(){sizeHandler();s_oGame&&s_oGame.showPausePanel(!1);s_oMain.startUpdate();sizeHandler()});$(window).blur(function(){s_oGame&&s_oGame.showPausePanel(!0);s_oMain.stopUpdate()});$(window).focus(function(){s_oGame&&s_oGame.showPausePanel(!1);s_oMain.startUpdate()});function trace(a){console.log(a)}
function getSize(a){var c=a.toLowerCase(),d=window.document,b=d.documentElement;if(void 0===window["inner"+a])a=b["client"+a];else if(window["inner"+a]!=b["client"+a]){var f=d.createElement("body");f.id="vpw-test-b";f.style.cssText="overflow:scroll";var h=d.createElement("div");h.id="vpw-test-d";h.style.cssText="position:absolute;top:-1000px";h.innerHTML="<style>@media("+c+":"+b["client"+a]+"px){body#vpw-test-b div#vpw-test-d{"+c+":7px!important}}</style>";f.appendChild(h);b.insertBefore(f,d.head);
a=7==h["offset"+a]?b["client"+a]:window["inner"+a];b.removeChild(f)}else a=window["inner"+a];return a}window.addEventListener("orientationchange",onOrientationChange);function onOrientationChange(){window.matchMedia("(orientation: portrait)").matches&&sizeHandler();window.matchMedia("(orientation: landscape)").matches&&sizeHandler()}function isChrome(){return/Chrome/.test(navigator.userAgent)&&/Google Inc/.test(navigator.vendor)}
function isIOS(){var a="iPad Simulator;iPhone Simulator;iPod Simulator;iPad;iPhone;iPod".split(";");for(-1!==navigator.userAgent.toLowerCase().indexOf("iphone")&&(s_bIsIphone=!0);a.length;)if(navigator.platform===a.pop())return!0;return s_bIsIphone=!1}function getIOSWindowHeight(){return document.documentElement.clientWidth/window.innerWidth*window.innerHeight}function getHeightOfIOSToolbars(){var a=(0===window.orientation?screen.height:screen.width)-getIOSWindowHeight();return 1<a?a:0}
function sizeHandler(){window.scrollTo(0,1);if($("#canvas")){var a=navigator.userAgent.match(/(iPad|iPhone|iPod)/g)?getIOSWindowHeight():getSize("Height");var c=getSize("Width");_checkOrientation(c,a);var d=Math.min(a/CANVAS_HEIGHT,c/CANVAS_WIDTH),b=CANVAS_WIDTH*d;d*=CANVAS_HEIGHT;if(d<a){var f=a-d;d+=f;b+=CANVAS_WIDTH/CANVAS_HEIGHT*f}else b<c&&(f=c-b,b+=f,d+=CANVAS_HEIGHT/CANVAS_WIDTH*f);f=a/2-d/2;var h=c/2-b/2,g=CANVAS_WIDTH/b;if(h*g<-EDGEBOARD_X||f*g<-EDGEBOARD_Y)d=Math.min(a/(CANVAS_HEIGHT-2*
EDGEBOARD_Y),c/(CANVAS_WIDTH-2*EDGEBOARD_X)),b=CANVAS_WIDTH*d,d*=CANVAS_HEIGHT,f=(a-d)/2,h=(c-b)/2,g=CANVAS_WIDTH/b;s_iOffsetX=-1*h*g;s_iOffsetY=-1*f*g;0<=f&&(s_iOffsetY=0);0<=h&&(s_iOffsetX=0);null!==s_oInterface&&s_oInterface.refreshButtonPos(s_iOffsetX,s_iOffsetY);null!==s_oMenu&&s_oMenu.refreshButtonPos(s_iOffsetX,s_iOffsetY);s_bIsIphone?(canvas=document.getElementById("canvas"),s_oStage.canvas.width=2*b,s_oStage.canvas.height=2*d,canvas.style.width=b+"px",canvas.style.height=d+"px",s_iScaleFactor=
2*Math.min(b/CANVAS_WIDTH,d/CANVAS_HEIGHT),s_oStage.scaleX=s_oStage.scaleY=s_iScaleFactor):s_bMobile||isChrome()?($("#canvas").css("width",b+"px"),$("#canvas").css("height",d+"px")):(s_oStage.canvas.width=b,s_oStage.canvas.height=d,s_iScaleFactor=Math.min(b/CANVAS_WIDTH,d/CANVAS_HEIGHT),s_oStage.scaleX=s_oStage.scaleY=s_iScaleFactor);0>f?$("#canvas").css("top",f+"px"):$("#canvas").css("top","0px");$("#canvas").css("left",h+"px");fullscreenHandler()}}
function _checkOrientation(a,c){s_bMobile&&ENABLE_CHECK_ORIENTATION&&(a>c?"landscape"===$(".orientation-msg-container").attr("data-orientation")?($(".orientation-msg-container").css("display","none"),s_oMain.startUpdate()):($(".orientation-msg-container").css("display","block"),s_oMain.stopUpdate()):"portrait"===$(".orientation-msg-container").attr("data-orientation")?($(".orientation-msg-container").css("display","none"),s_oMain.startUpdate()):($(".orientation-msg-container").css("display","block"),
s_oMain.stopUpdate()))}function inIframe(){try{return window.self!==window.top}catch(a){return!0}}function playSound(a,c,d){return!1===DISABLE_SOUND_MOBILE||!1===s_bMobile?(s_aSounds[a].play(),s_aSounds[a].volume(c),s_aSounds[a].loop(d),s_aSounds[a]):null}function stopSound(a){!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||s_aSounds[a].stop()}function setVolume(a,c){!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||s_aSounds[a].volume(c)}
function setMute(a,c){!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||s_aSounds[a].mute(c)}function fadeSound(a,c,d,b){!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||s_aSounds[a].fade(c,d,b)}function soundPlaying(a){if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)return s_aSounds[a].playing()}function createBitmap(a,c,d){var b=new createjs.Bitmap(a),f=new createjs.Shape;c&&d?f.graphics.beginFill("#fff").drawRect(0,0,c,d):f.graphics.beginFill("#ff0").drawRect(0,0,a.width,a.height);b.hitArea=f;return b}
function createSprite(a,c,d,b,f,h){a=null!==c?new createjs.Sprite(a,c):new createjs.Sprite(a);c=new createjs.Shape;c.graphics.beginFill("#000000").drawRect(-d,-b,f,h);a.hitArea=c;return a}function randomFloatBetween(a,c,d){"undefined"===typeof d&&(d=2);return parseFloat(Math.min(a+Math.random()*(c-a),c).toFixed(d))}function rotateVector2D(a,c){var d=c.getX()*Math.cos(a)+c.getY()*Math.sin(a),b=c.getX()*-Math.sin(a)+c.getY()*Math.cos(a);c.set(d,b)}function tweenVectorsOnX(a,c,d){return a+d*(c-a)}
function shuffle(a){for(var c=a.length,d,b;0!==c;)b=Math.floor(Math.random()*c),--c,d=a[c],a[c]=a[b],a[b]=d;return a}function bubbleSort(a){do{var c=!1;for(var d=0;d<a.length-1;d++)a[d]>a[d+1]&&(c=a[d],a[d]=a[d+1],a[d+1]=c,c=!0)}while(c)}function compare(a,c){return a.index>c.index?-1:a.index<c.index?1:0}function easeLinear(a,c,d,b){return d*a/b+c}function easeInQuad(a,c,d,b){return d*(a/=b)*a+c}function easeInSine(a,c,d,b){return-d*Math.cos(a/b*(Math.PI/2))+d+c}
function easeInCubic(a,c,d,b){return d*(a/=b)*a*a+c}function getTrajectoryPoint(a,c){var d=new createjs.Point,b=(1-a)*(1-a),f=a*a;d.x=b*c.start.x+2*(1-a)*a*c.traj.x+f*c.end.x;d.y=b*c.start.y+2*(1-a)*a*c.traj.y+f*c.end.y;return d}function formatTime(a){a/=1E3;var c=Math.floor(a/60);a=Math.floor(a-60*c);var d="";d=10>c?d+("0"+c+":"):d+(c+":");return 10>a?d+("0"+a):d+a}function degreesToRadians(a){return a*Math.PI/180}
function checkRectCollision(a,c){var d=getBounds(a,.9);var b=getBounds(c,.98);return calculateIntersection(d,b)}function calculateIntersection(a,c){var d,b,f,h;var g=a.x+(d=a.width/2);var k=a.y+(b=a.height/2);var e=c.x+(f=c.width/2);var l=c.y+(h=c.height/2);g=Math.abs(g-e)-(d+f);k=Math.abs(k-l)-(b+h);return 0>g&&0>k?(g=Math.min(Math.min(a.width,c.width),-g),k=Math.min(Math.min(a.height,c.height),-k),{x:Math.max(a.x,c.x),y:Math.max(a.y,c.y),width:g,height:k,rect1:a,rect2:c}):null}
function dlx_cover(a){a.right.left=a.left;a.left.right=a.right;for(var c=a.down;c!==a;c=c.down)for(var d=c.right;d!==c;d=d.right)d.down.up=d.up,d.up.down=d.down,d.column.size--}function dlx_uncover(a){for(var c=a.up;c!==a;c=c.up)for(var d=c.left;d!==c;d=d.left)d.column.size++,d.down.up=d,d.up.down=d;a.right.left=a;a.left.right=a}
function dlx_search(a,c,d,b,f){if(a.right===a)return b.push(c.slice(0)),b.length>=f?b:null;for(var h=null,g=99999,k=a.right;k!==a;k=k.right){if(0===k.size)return null;k.size<g&&(g=k.size,h=k)}dlx_cover(h);for(var e=h.down;e!==h;e=e.down){c[d]=e.row;for(k=e.right;k!==e;k=k.right)dlx_cover(k.column);g=dlx_search(a,c,d+1,b,f);if(null!==g)return g;for(k=e.left;k!==e;k=k.left)dlx_uncover(k.column)}dlx_uncover(h);return null}
function dlx_solve(a,c,d){for(var b=Array(a[0].length),f=0;f<b.length;f++)b[f]={};for(f=0;f<b.length;f++)b[f].index=f,b[f].up=b[f],b[f].down=b[f],f>=c?(f-1>=c&&(b[f].left=b[f-1]),f+1<b.length&&(b[f].right=b[f+1])):(b[f].left=b[f],b[f].right=b[f]),b[f].size=0;for(f=0;f<a.length;f++)for(var h=null,g=0;g<a[f].length;g++)if(a[f][g]){var k={};k.row=f;k.column=b[g];k.up=b[g].up;k.down=b[g];h?(k.left=h,k.right=h.right,h.right.left=k,h.right=k):(k.left=k,k.right=k);b[g].up.down=k;b[g].up=k;b[g].size++;h=
k}a={};a.right=b[c];a.left=b[b.length-1];b[c].left=a;b[b.length-1].right=a;solutions=[];dlx_search(a,[],0,solutions,d);return solutions}
function solve_sudoku(a){for(var c=[],d=[],b=0;9>b;b++)for(var f=0;9>f;f++){var h=a[b][f]-1;if(0<=h){var g=Array(324);g[9*b+f]=1;g[81+9*b+h]=1;g[162+9*f+h]=1;g[243+9*(3*Math.floor(b/3)+Math.floor(f/3))+h]=1;c.push(g);d.push({row:b,col:f,n:h+1})}else for(h=0;9>h;h++)g=Array(324),g[9*b+f]=1,g[81+9*b+h]=1,g[162+9*f+h]=1,g[243+9*(3*Math.floor(b/3)+Math.floor(f/3))+h]=1,c.push(g),d.push({row:b,col:f,n:h+1})}c=dlx_solve(c,0,2);if(0<c.length){f=c[0];for(b=0;b<f.length;b++)a[d[f[b]].row][d[f[b]].col]=d[f[b]].n;
return c.length}return 0}function solve(a){a=solve_sudoku(a);if(0<a){if(1<a)return 1}else return trace("no solution"),0}
function getBounds(a,c){var d={x:Infinity,y:Infinity,width:0,height:0};if(a instanceof createjs.Container){d.x2=-Infinity;d.y2=-Infinity;var b=a.children,f=b.length,h;for(h=0;h<f;h++){var g=getBounds(b[h],1);g.x<d.x&&(d.x=g.x);g.y<d.y&&(d.y=g.y);g.x+g.width>d.x2&&(d.x2=g.x+g.width);g.y+g.height>d.y2&&(d.y2=g.y+g.height)}Infinity==d.x&&(d.x=0);Infinity==d.y&&(d.y=0);Infinity==d.x2&&(d.x2=0);Infinity==d.y2&&(d.y2=0);d.width=d.x2-d.x;d.height=d.y2-d.y;delete d.x2;delete d.y2}else{if(a instanceof createjs.Bitmap){f=
a.sourceRect||a.image;h=f.width*c;var k=f.height*c}else if(a instanceof createjs.Sprite)if(a.spriteSheet._frames&&a.spriteSheet._frames[a.currentFrame]&&a.spriteSheet._frames[a.currentFrame].image){f=a.spriteSheet.getFrame(a.currentFrame);h=f.rect.width;k=f.rect.height;b=f.regX;var e=f.regY}else d.x=a.x||0,d.y=a.y||0;else d.x=a.x||0,d.y=a.y||0;b=b||0;h=h||0;e=e||0;k=k||0;d.regX=b;d.regY=e;f=a.localToGlobal(0-b,0-e);g=a.localToGlobal(h-b,k-e);h=a.localToGlobal(h-b,0-e);b=a.localToGlobal(0-b,k-e);d.x=
Math.min(Math.min(Math.min(f.x,g.x),h.x),b.x);d.y=Math.min(Math.min(Math.min(f.y,g.y),h.y),b.y);d.width=Math.max(Math.max(Math.max(f.x,g.x),h.x),b.x)-d.x;d.height=Math.max(Math.max(Math.max(f.y,g.y),h.y),b.y)-d.y}return d}function NoClickDelay(a){this.element=a;window.Touch&&this.element.addEventListener("touchstart",this,!1)}function shuffle(a){for(var c=a.length,d,b;0<c;)b=Math.floor(Math.random()*c),c--,d=a[c],a[c]=a[b],a[b]=d;return a}
NoClickDelay.prototype={handleEvent:function(a){switch(a.type){case "touchstart":this.onTouchStart(a);break;case "touchmove":this.onTouchMove(a);break;case "touchend":this.onTouchEnd(a)}},onTouchStart:function(a){a.preventDefault();this.moved=!1;this.element.addEventListener("touchmove",this,!1);this.element.addEventListener("touchend",this,!1)},onTouchMove:function(a){this.moved=!0},onTouchEnd:function(a){this.element.removeEventListener("touchmove",this,!1);this.element.removeEventListener("touchend",
this,!1);if(!this.moved){a=document.elementFromPoint(a.changedTouches[0].clientX,a.changedTouches[0].clientY);3==a.nodeType&&(a=a.parentNode);var c=document.createEvent("MouseEvents");c.initEvent("click",!0,!0);a.dispatchEvent(c)}}};
(function(){function a(a){var b={focus:"visible",focusin:"visible",pageshow:"visible",blur:"hidden",focusout:"hidden",pagehide:"hidden"};a=a||window.event;a.type in b?document.body.className=b[a.type]:(document.body.className=this[c]?"hidden":"visible","hidden"===document.body.className?s_oMain.stopUpdate():s_oMain.startUpdate())}var c="hidden";c in document?document.addEventListener("visibilitychange",a):(c="mozHidden")in document?document.addEventListener("mozvisibilitychange",a):(c="webkitHidden")in
document?document.addEventListener("webkitvisibilitychange",a):(c="msHidden")in document?document.addEventListener("msvisibilitychange",a):"onfocusin"in document?document.onfocusin=document.onfocusout=a:window.onpageshow=window.onpagehide=window.onfocus=window.onblur=a})();function ctlArcadeResume(){null!==s_oMain&&s_oMain.startUpdate()}function ctlArcadePause(){null!==s_oMain&&s_oMain.stopUpdate()}
function getParamValue(a){for(var c=window.location.search.substring(1).split("&"),d=0;d<c.length;d++){var b=c[d].split("=");if(b[0]==a)return b[1]}}function fullscreenHandler(){ENABLE_FULLSCREEN&&screenfull.enabled&&(s_bFullscreen=screen.height<window.innerHeight+3&&screen.height>window.innerHeight-3?!0:!1,null!==s_oInterface&&s_oInterface.resetFullscreenBut(),null!==s_oMenu&&s_oMenu.resetFullscreenBut())}
if(screenfull.enabled)screenfull.on("change",function(){s_bFullscreen=screenfull.isFullscreen;null!==s_oInterface&&s_oInterface.resetFullscreenBut();null!==s_oMenu&&s_oMenu.resetFullscreenBut()});
function CSpriteLibrary(){var a,c,d,b,f,h;this.init=function(g,k,e){d=c=0;b=g;f=k;h=e;a={}};this.addSprite=function(b,f){a.hasOwnProperty(b)||(a[b]={szPath:f,oSprite:new Image},c++)};this.getSprite=function(b){return a.hasOwnProperty(b)?a[b].oSprite:null};this._onSpritesLoaded=function(){f.call(h)};this._onSpriteLoaded=function(){b.call(h);++d==c&&this._onSpritesLoaded()};this.loadSprites=function(){for(var b in a)a[b].oSprite.oSpriteLibrary=this,a[b].oSprite.onload=function(){this.oSpriteLibrary._onSpriteLoaded()},
a[b].oSprite.src=a[b].szPath};this.getNumSprites=function(){return c}}
var CANVAS_WIDTH=1080,CANVAS_HEIGHT=1920,EDGEBOARD_X=25,EDGEBOARD_Y=200,CELL_SIZE=106,FPS=30,FPS_TIME=1E3/FPS,DISABLE_SOUND_MOBILE=!1,PRIMARY_FONT="Arial",SECONDARY_FONT="blackplotan",PRIMARY_FONT_COLOUR="#008df0",TIME_LOOP_WAIT=2E3,STATE_LOADING=0,STATE_MENU=1,STATE_HELP=1,STATE_GAME=3,EASY_MODE=0,MEDIUM_MODE=1,HARD_MODE=2,ON_MOUSE_DOWN=0,ON_MOUSE_UP=1,ON_MOUSE_OVER=2,ON_MOUSE_OUT=3,ON_DRAG_START=4,ON_DRAG_END=5,MAX_GIVENS_EASY,MAX_GIVENS_MEDIUM,MAX_GIVENS_HARD,RANGE_GIVENS=0,LOWER_BOUND_EASY=4,
LOWER_BOUND_MEDIUM=3,LOWER_BOUND_HARD=2,TIME_BONUS_LIMIT=[],ENABLE_FULLSCREEN,ENABLE_CHECK_ORIENTATION;TEXT_PRELOADER_CONTINUE="START";TEXT_GAMEOVER="YOU COMPLETED ";TEXT_ARE_SURE="ARE YOU SURE?";TEXT_SUDOKU=" SUDOKU";TEXT_IN=" IN ";TEXT_HELP_USED="YOU USED THE FOLLOWING HELP:";TEXT_HELPS_USED="YOU USED THE FOLLOWING HELPS:";TEXT_HELP_NOTE="NOTES AUTOFILL";TEXT_HELP_SOLVE="SOLVER";TEXT_HELP_TIME="SET NO TIME";TEXT_HELP_HINT=" HINT";TEXT_HELP_HINTS=" HINTS";TEXT_SCORE="SCORE:";TEXT_PLAY="PLAY";
TEXT_RESTART="RESTART";TEXT_TIME="TIME";TEXT_GENERATE_SUDOKU="GENERATING SUDOKU. PLEASE WAIT";TEXT_PAUSE="PAUSE";TEXT_DEVELOPED="DEVELOPED BY";TEXT_INFO_SOLVE="(all points lost)";TEXT_INFO_NOTE="(half of all points lost)";TEXT_INFO_HINT="points per hint)";TEXT_TOP_MODE="SELECT YOUR LEVEL";TEXT_EASY="BEGINNER";TEXT_MEDIUM="INTERMEDIATE";TEXT_HARD="ADVANCED";TEXT_HELP0="RULES";TEXT_HELP1="FILL IN THE BLANKS WITH NUMBERS FROM 1 TO 9. EACH ROW, COLUMN OR 3X3 BLOCK, MUST CONTAIN THE NUMBER 1 THROUGH 9 EXACTLY ONCE";
TEXT_HELP0_PAGE2="HOW-TO";TEXT_HELP1_PAGE2="USE KEYBOARD OR NUMBER BUTTONS TO FILL IN THE BLANKS. THERE ARE 3 DIFFERENT GAME MODES:";TEXT_HELP1_MOB_PAGE2="USE NUMBER BUTTONS TO FILL BLANKS IN GAME. THERE ARE 3 DIFFERENT GAME MODES:";TEXT_HELP2_PAGE2='"CELL FIRST" MODE: CLICK FIRST THE CELL YOU WANT TO FILL IN, THEN SELECT THE NUMBER YOU WANT TO ENTER';TEXT_HELP3_PAGE2='"NUMBER FIRST" MODE: SELECT THE NUMBER YOU WANT TO ENTER FIRST, THEN CLICK THE CELL YOU WANT TO FILL IN';TEXT_HELP4_PAGE2="MEMO MODE: THIS BUTTON ALLOWS YOU TO WRITE DOWN A MEMO IN A BLANK";
TEXT_FILL_WITH_NOTE="FILL THE BOARD WITH NOTES";TEXT_DELETE_ALL_NOTE="DELETE ALL NOTES";TEXT_SOLVE="SOLVE THE SUDOKU";TEXT_RESET="RESET THE SUDOKU";TEXT_SETNOTIME="PLAY WITHOUT TIME";TEXT_GETHINT="GET A HINT";TEXT_FULLSCREEN="FULL SCREEN";TEXT_SHARE_IMAGE="200x200.jpg";TEXT_SHARE_TITLE="Congratulations!";TEXT_SHARE_MSG1="You collected <strong>";TEXT_SHARE_MSG2=" points</strong>!<br><br>Share your score with your friends!";TEXT_SHARE_SHARE1="My score is ";TEXT_SHARE_SHARE2=" points! Can you do better";
function CPreloader(){var a,c,d,b,f,h,g,k,e,l;this._init=function(){s_oSpriteLibrary.init(this._onImagesLoaded,this._onAllImagesLoaded,this);s_oSpriteLibrary.addSprite("progress_bar","./sprites/progress_bar.png");s_oSpriteLibrary.addSprite("200x200","./sprites/200x200.jpg");s_oSpriteLibrary.addSprite("but_start","./sprites/but_start.png");s_oSpriteLibrary.loadSprites();l=new createjs.Container;s_oStage.addChild(l)};this.unload=function(){l.removeAllChildren();e.unload()};this._onImagesLoaded=function(){};
this._onAllImagesLoaded=function(){this.attachSprites();s_oMain.preloaderReady()};this.attachSprites=function(){var m=new createjs.Shape;m.graphics.beginFill("black").drawRect(0,0,CANVAS_WIDTH,CANVAS_HEIGHT);l.addChild(m);m=s_oSpriteLibrary.getSprite("200x200");g=createBitmap(m);g.regX=.5*m.width;g.regY=.5*m.height;g.x=CANVAS_WIDTH/2;g.y=CANVAS_HEIGHT/2-180;l.addChild(g);k=new createjs.Shape;k.graphics.beginFill("rgba(0,0,0,0.01)").drawRoundRect(g.x-100,g.y-100,200,200,10);l.addChild(k);g.mask=k;
m=s_oSpriteLibrary.getSprite("progress_bar");b=createBitmap(m);b.x=CANVAS_WIDTH/2-m.width/2;b.y=CANVAS_HEIGHT/2+50;l.addChild(b);a=m.width;c=m.height;f=new createjs.Shape;f.graphics.beginFill("rgba(0,0,0,0.01)").drawRect(b.x,b.y,1,c);l.addChild(f);b.mask=f;d=new createjs.Text("","30px "+PRIMARY_FONT,PRIMARY_FONT_COLOUR);d.x=CANVAS_WIDTH/2;d.y=CANVAS_HEIGHT/2+100;d.textBaseline="alphabetic";d.textAlign="center";l.addChild(d);m=s_oSpriteLibrary.getSprite("but_start");e=new CTextButton(CANVAS_WIDTH/
2,CANVAS_HEIGHT/2,m,TEXT_PRELOADER_CONTINUE,"Arial","#000","bold 50",l);e.addEventListener(ON_MOUSE_UP,this._onButStartRelease,this);e.setTextPosition(62);e.setVisible(!1);h=new createjs.Shape;h.graphics.beginFill("black").drawRect(0,0,CANVAS_WIDTH,CANVAS_HEIGHT);l.addChild(h);createjs.Tween.get(h).to({alpha:0},500).call(function(){createjs.Tween.removeTweens(h);l.removeChild(h)})};this._onButStartRelease=function(){s_oMain._onRemovePreloader()};this.refreshLoader=function(l){d.text=l+"%";100===l&&
(e.setVisible(!0),d.visible=!1,b.visible=!1);f.graphics.clear();l=Math.floor(l*a/100);f.graphics.beginFill("rgba(0,0,0,0.01)").drawRect(b.x,b.y,l,c)};this._init()}
function CMain(a){var c,d=0,b=0,f=STATE_LOADING,h,g;this.initContainer=function(){s_oCanvas=document.getElementById("canvas");s_oStage=new createjs.Stage(s_oCanvas);s_oStage.preventSelection=!1;createjs.Touch.enable(s_oStage);s_bMobile=jQuery.browser.mobile;!1===s_bMobile&&(s_oStage.enableMouseOver(20),$("body").on("contextmenu","#canvas",function(a){return!1}));s_iPrevTime=(new Date).getTime();createjs.Ticker.addEventListener("tick",this._update);createjs.Ticker.framerate=FPS;navigator.userAgent.match(/Windows Phone/i)&&
(DISABLE_SOUND_MOBILE=!0);s_oSpriteLibrary=new CSpriteLibrary;h=new CPreloader};this.preloaderReady=function(){!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||this._initSounds();this._loadImages()};this.soundLoaded=function(){d++;h.refreshLoader(Math.floor(d/b*100))};this._initSounds=function(){var a=[];a.push({path:"./sounds/",filename:"press_button",loop:!1,volume:1,ingamename:"click"});a.push({path:"./sounds/",filename:"game_over",
loop:!1,volume:1,ingamename:"game_over"});b+=a.length;s_aSounds=[];for(var c=0;c<a.length;c++)s_aSounds[a[c].ingamename]=new Howl({src:[a[c].path+a[c].filename+".mp3",a[c].path+a[c].filename+".ogg"],autoplay:!1,preload:!0,loop:a[c].loop,volume:a[c].volume,onload:s_oMain.soundLoaded})};this._loadImages=function(){s_oSpriteLibrary.init(this._onImagesLoaded,this._onAllImagesLoaded,this);s_oSpriteLibrary.addSprite("but_play","./sprites/but_play.png");s_oSpriteLibrary.addSprite("msg_box","./sprites/msg_box.png");
s_oSpriteLibrary.addSprite("but_credits","./sprites/but_credits.png");s_oSpriteLibrary.addSprite("ctl_logo","./sprites/ctl_logo.png");s_oSpriteLibrary.addSprite("bg_menu","./sprites/bg_menu.jpg");s_oSpriteLibrary.addSprite("bg_mode_menu","./sprites/bg_mode_menu.jpg");s_oSpriteLibrary.addSprite("mod_easy_icon","./sprites/mod_easy_icon.png");s_oSpriteLibrary.addSprite("mod_medium_icon","./sprites/mod_medium_icon.png");s_oSpriteLibrary.addSprite("mod_hard_icon","./sprites/mod_hard_icon.png");s_oSpriteLibrary.addSprite("bg_game",
"./sprites/bg_game.jpg");s_oSpriteLibrary.addSprite("bg_help","./sprites/bg_help.png");s_oSpriteLibrary.addSprite("bg_help2","./sprites/bg_help2.png");s_oSpriteLibrary.addSprite("arrow","./sprites/arrow.png");s_oSpriteLibrary.addSprite("but_yes","./sprites/but_yes.png");s_oSpriteLibrary.addSprite("but_exit","./sprites/but_exit.png");s_oSpriteLibrary.addSprite("audio_icon","./sprites/audio_icon.png");s_oSpriteLibrary.addSprite("config_icon","./sprites/config_icon.png");s_oSpriteLibrary.addSprite("but_help_icon",
"./sprites/but_help_icon.png");s_oSpriteLibrary.addSprite("but_help_note","./sprites/but_help_note.png");s_oSpriteLibrary.addSprite("but_del_note","./sprites/but_del_note.png");s_oSpriteLibrary.addSprite("but_solve","./sprites/but_solve.png");s_oSpriteLibrary.addSprite("but_reset","./sprites/but_reset.png");s_oSpriteLibrary.addSprite("but_time","./sprites/but_time.png");s_oSpriteLibrary.addSprite("but_help_hint","./sprites/but_help_hint.png");s_oSpriteLibrary.addSprite("time_display","./sprites/time_display.png");
s_oSpriteLibrary.addSprite("given_bg","./sprites/given_bg.png");s_oSpriteLibrary.addSprite("blank","./sprites/blank.png");s_oSpriteLibrary.addSprite("background","./sprites/background.png");s_oSpriteLibrary.addSprite("highlight","./sprites/highlight.png");s_oSpriteLibrary.addSprite("cell_selected","./sprites/cell_selected.png");s_oSpriteLibrary.addSprite("but_num","./sprites/but_num.png");s_oSpriteLibrary.addSprite("but_del_toggle","./sprites/but_del_toggle.png");s_oSpriteLibrary.addSprite("note_toggle",
"./sprites/note_toggle.png");s_oSpriteLibrary.addSprite("mode_toggle","./sprites/mode_toggle.png");s_oSpriteLibrary.addSprite("credit_bg","./sprites/credit_bg.png");s_oSpriteLibrary.addSprite("but_fullscreen","./sprites/but_fullscreen.png");s_oSpriteLibrary.addSprite("but_fullscreen_help","./sprites/but_fullscreen_help.png");b+=s_oSpriteLibrary.getNumSprites();s_oSpriteLibrary.loadSprites()};this._onImagesLoaded=function(){d++;h.refreshLoader(Math.floor(d/b*100))};this._onAllImagesLoaded=function(){};
this.onAllPreloaderImagesLoaded=function(){this._loadImages()};this._onRemovePreloader=function(){h.unload();this.gotoMenu()};this.gotoMenu=function(){new CMenu;f=STATE_MENU};this.goToModeMenu=function(){new CModeMenu;f=STATE_MENU};this.gotoGame=function(a){s_iDifficultyMode=a;g=new CGame(k);f=STATE_GAME};this.gotoHelp=function(){new CHelp;f=STATE_HELP};this.stopUpdate=function(){c=!1;createjs.Ticker.paused=!0;$("#block_game").css("display","block");Howler.mute(!0)};this.startUpdate=function(){s_iPrevTime=
(new Date).getTime();c=!0;createjs.Ticker.paused=!1;$("#block_game").css("display","none");s_bAudioActive&&Howler.mute(!1)};this._update=function(a){if(!1!==c){var b=(new Date).getTime();s_iTimeElaps=b-s_iPrevTime;s_iCntTime+=s_iTimeElaps;s_iCntFps++;s_iPrevTime=b;1E3<=s_iCntTime&&(s_iCurFps=s_iCntFps,s_iCntTime-=1E3,s_iCntFps=0);f===STATE_GAME&&g.update();s_oStage.update(a)}};s_oMain=this;var k=a;ENABLE_FULLSCREEN=a.fullscreen;ENABLE_CHECK_ORIENTATION=a.check_orientation;this.initContainer()}
var s_bMobile,s_iDifficultyMode,s_bAudioActive=!0,s_iCntTime=0,s_iTimeElaps=0,s_iPrevTime=0,s_iCntFps=0,s_iCurFps=0,s_oDrawLayer,s_oStage,s_oMain,s_oSpriteLibrary,s_oCanvas,s_bFullscreen=!1,s_aSounds;
function CTextButton(a,c,d,b,f,h,g,k){var e,l,m,p,r,n,q,u;this._init=function(a,b,c,f,d,h,g,k){e=[];l=[];var n=createBitmap(c),q=Math.ceil(g/20);u=new createjs.Text(f," "+g+"px "+d,"#000000");u.textAlign="center";u.textBaseline="alphabetic";var t=u.getBounds();u.x=c.width/2+q;u.y=Math.floor(c.height/2)+t.height/3+q;p=new createjs.Text(f," "+g+"px "+d,h);p.textAlign="center";p.textBaseline="alphabetic";t=p.getBounds();p.x=c.width/2;p.y=Math.floor(c.height/2)+t.height/3-9;m=new createjs.Container;m.x=
a;m.y=b;m.regX=c.width/2;m.regY=c.height/2;m.addChild(n,u,p);k.addChild(m);this._initListener()};this.unload=function(){m.off("mousedown",r);m.off("pressup",n);s_bMobile||m.off("mouseover",q);k.removeChild(m)};this.setVisible=function(a){m.visible=a};this._initListener=function(){r=m.on("mousedown",this.buttonDown);n=m.on("pressup",this.buttonRelease);s_bMobile||(q=m.on("mouseover",this.buttonOver))};this.addEventListener=function(a,b,c){e[a]=b;l[a]=c};this.buttonRelease=function(){m.scaleX=1;m.scaleY=
1;e[ON_MOUSE_UP]&&e[ON_MOUSE_UP].call(l[ON_MOUSE_UP])};this.buttonDown=function(){m.scaleX=.9;m.scaleY=.9;playSound("click",1,!1);e[ON_MOUSE_DOWN]&&e[ON_MOUSE_DOWN].call(l[ON_MOUSE_DOWN])};this.buttonOver=function(a){s_bMobile||(a.target.cursor="pointer")};this.setNoShadow=function(){m.removeChild(u)};this.setTextPosition=function(a){p.y=a;u.y=a+2};this.setPosition=function(a,b){m.x=a;m.y=b};this.setX=function(a){m.x=a};this.setY=function(a){m.y=a};this.getButtonImage=function(){return m};this.getX=
function(){return m.x};this.getY=function(){return m.y};this._init(a,c,d,b,f,h,g,k);return this}
function CToggle(a,c,d,b,f){var h,g,k,e,l,m,p;this._init=function(a,b,c,f){g=[];k=[];var d=new createjs.SpriteSheet({images:[c],frames:{width:c.width/2,height:c.height,regX:c.width/2/2,regY:c.height/2},animations:{state_true:[0],state_false:[1]}});h=f;e=createSprite(d,"state_"+h,c.width/2/2,c.height/2,c.width/2,c.height);e.x=a;e.y=b;e.stop();r.addChild(e);this._initListener()};this.unload=function(){e.off("mousedown",l);e.off("pressup",m);s_bMobile||e.off("mouseover",p);r.removeChild(e)};this._initListener=
function(){l=e.on("mousedown",this.buttonDown);m=e.on("pressup",this.buttonRelease);s_bMobile||(p=e.on("mouseover",this.buttonOver))};this.addEventListener=function(a,b,c){g[a]=b;k[a]=c};this.setActive=function(a){h=a;e.gotoAndStop("state_"+h)};this.buttonRelease=function(){e.scaleX=1;e.scaleY=1;playSound("click",1,!1);h=!h;e.gotoAndStop("state_"+h);g[ON_MOUSE_UP]&&g[ON_MOUSE_UP].call(k[ON_MOUSE_UP],h)};this.buttonDown=function(){e.scaleX=.9;e.scaleY=.9;g[ON_MOUSE_DOWN]&&g[ON_MOUSE_DOWN].call(k[ON_MOUSE_DOWN])};
this.buttonOver=function(a){s_bMobile||(a.target.cursor="pointer")};this.setPosition=function(a,b){e.x=a;e.y=b};var r=f;this._init(a,c,d,b)}
function CDeleteButton(a,c,d,b){var f,h,g,k,e,l,m,p;this._init=function(a,b,c,d){h=!0;g=[];k=[];var l=new createjs.SpriteSheet({images:[c],frames:{width:c.width/2,height:c.height,regX:c.width/2/2,regY:c.height/2},animations:{state_true:[0],state_false:[1]}});f=d;e=createSprite(l,"state_"+f,c.width/2/2,c.height/2,c.width/2,c.height);e.x=a;e.y=b;e.stop();s_oStage.addChild(e);this._initListener()};this.unload=function(){e.off("mousedown",l);e.off("pressup",m);s_bMobile||e.off("mouseover",p);s_oStage.removeChild(e)};
this.changeMode=function(){h=!h;f=!1;e.gotoAndStop("state_"+f)};this.reset=function(){f=!1;e.gotoAndStop("state_"+f)};this._initListener=function(){l=e.on("mousedown",this.buttonDown);m=e.on("pressup",this.buttonRelease);s_bMobile||(p=e.on("mouseover",this.buttonOver))};this.buttonOver=function(a){s_bMobile||(a.target.cursor="pointer")};this.addEventListener=function(a,c,b){g[a]=c;k[a]=b};this.setActive=function(a){f=a;e.gotoAndStop("state_"+f)};this.buttonRelease=function(){e.scaleX=1;e.scaleY=1;
h?(s_oInterface.setAllBlackColor(),f=!0,e.gotoAndStop("state_"+f),s_oGame.setDeleteState()):s_oGame.deleteCell();g[ON_MOUSE_UP]&&g[ON_MOUSE_UP].call(k[ON_MOUSE_UP],f)};this.buttonDown=function(){e.scaleX=.9;e.scaleY=.9;g[ON_MOUSE_DOWN]&&g[ON_MOUSE_DOWN].call(k[ON_MOUSE_DOWN])};this.setPosition=function(a,c){e.x=a;e.y=c};this._init(a,c,d,b)}
function CGfxButton(a,c,d,b){var f,h,g,k,e,l,m,p,r;this._init=function(a,c,b,e){f=1;h=[];g=[];k=createBitmap(b);k.x=a;k.y=c;k.regX=b.width/2;k.regY=b.height/2;p=e;p.addChild(k);this._initListener()};this.unload=function(){k.off("mousedown",e);k.off("pressup",l);s_bMobile||k.off("mouseover",m);p.removeChild(k)};this.setVisible=function(a){k.visible=a};this._initListener=function(){e=k.on("mousedown",this.buttonDown);l=k.on("pressup",this.buttonRelease);s_bMobile||(m=k.on("mouseover",this.buttonOver))};
this.addEventListener=function(a,c,b){h[a]=c;g[a]=b};this.buttonRelease=function(){r||(k.scaleX=f,k.scaleY=f);h[ON_MOUSE_UP]&&h[ON_MOUSE_UP].call(g[ON_MOUSE_UP])};this.buttonDown=function(){r||(k.scaleX=.9*f,k.scaleY=.9*f);playSound("click",1,!1);h[ON_MOUSE_DOWN]&&h[ON_MOUSE_DOWN].call(g[ON_MOUSE_DOWN])};this.buttonOver=function(a){s_bMobile||(a.target.cursor="pointer")};this.pulseAnimation=function(){r=createjs.Tween.get(k,{loop:!0}).to({scaleX:1.1*f,scaleY:1.1*f},850,createjs.Ease.quadOut).to({scaleX:f,
scaleY:f},650,createjs.Ease.quadIn)};this.setPosition=function(a,c){k.x=a;k.y=c};this.setX=function(a){k.x=a};this.setY=function(a){k.y=a};this.getButtonImage=function(){return k};this.getX=function(){return k.x};this.getY=function(){return k.y};this._init(a,c,d,b);return this}
function CMenu(){var a,c,d,b,f,h,g,k,e,l,m,p,r=null,n=null;this._init=function(){g=createBitmap(s_oSpriteLibrary.getSprite("bg_menu"));s_oStage.addChild(g);var q=s_oSpriteLibrary.getSprite("but_play");k=new CTextButton(CANVAS_WIDTH/2,CANVAS_HEIGHT-600,q,TEXT_PLAY,SECONDARY_FONT,"#ffffff",130,s_oStage);k.addEventListener(ON_MOUSE_UP,this._onButPlayRelease,this);k.setNoShadow();if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)q=s_oSpriteLibrary.getSprite("audio_icon"),f=CANVAS_WIDTH-q.height/2-10,h=q.height/
2+10,l=new CToggle(f,h,q,s_bAudioActive,s_oStage),l.addEventListener(ON_MOUSE_UP,this._onAudioToggle,this);q=s_oSpriteLibrary.getSprite("but_credits");d=q.height/2+10;b=q.height/2+10;m=new CGfxButton(d,b,q,s_oStage);m.addEventListener(ON_MOUSE_UP,this._onButCreditRelease,this);q=window.document;var u=q.documentElement;r=u.requestFullscreen||u.mozRequestFullScreen||u.webkitRequestFullScreen||u.msRequestFullscreen;n=q.exitFullscreen||q.mozCancelFullScreen||q.webkitExitFullscreen||q.msExitFullscreen;
!1===ENABLE_FULLSCREEN&&(r=!1);r&&screenfull.enabled&&(q=s_oSpriteLibrary.getSprite("but_fullscreen"),a=d+q.width/2+10,c=b,p=new CToggle(a,c,q,s_bFullscreen,s_oStage),p.addEventListener(ON_MOUSE_UP,this._onFullscreenRelease,this));e=new createjs.Shape;e.graphics.beginFill("black").drawRect(0,0,CANVAS_WIDTH,CANVAS_HEIGHT);s_oStage.addChild(e);createjs.Tween.get(e).to({alpha:0},1E3).call(function(){e.visible=!1});this.refreshButtonPos(s_iOffsetX,s_iOffsetY)};this.unload=function(){k.unload();k=null;
if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)l.unload(),l=null;r&&screenfull.enabled&&p.unload();s_oStage.removeChild(g);s_oMenu=g=null};this.refreshButtonPos=function(e,g){m.setPosition(d+e,g+b);!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||l.setPosition(f-e,g+h);r&&screenfull.enabled&&p.setPosition(a+e,c+g)};this._onAudioToggle=function(){Howler.mute(s_bAudioActive);s_bAudioActive=!s_bAudioActive};this._onButPlayRelease=function(){this.unload();$(s_oMain).trigger("start_session");s_oMain.goToModeMenu()};
this._onButCreditRelease=function(){new CCreditsPanel};this.resetFullscreenBut=function(){r&&screenfull.enabled&&p.setActive(s_bFullscreen)};this._onFullscreenRelease=function(){s_bFullscreen?n.call(window.document):r.call(window.document.documentElement);sizeHandler()};s_oMenu=this;this._init()}var s_oMenu=null;
function CModeMenu(){var a,c,d,b,f,h,g,k,e,l,m,p;this._init=function(){a=createBitmap(s_oSpriteLibrary.getSprite("bg_mode_menu"));s_oStage.addChild(a);m=new createjs.Text(TEXT_TOP_MODE," 100px "+SECONDARY_FONT,PRIMARY_FONT_COLOUR);m.x=CANVAS_WIDTH/2;m.y=200;m.textAlign="center";m.lineWidth=800;s_oStage.addChild(m);var n=CANVAS_WIDTH/2;c=new createjs.Container;c.x=n;c.y=350;d=new createjs.Container;d.x=n;d.y=800;b=new createjs.Container;b.x=n;b.y=1250;f=new createjs.Text(TEXT_EASY," 50px "+SECONDARY_FONT,
PRIMARY_FONT_COLOUR);f.textBaseline="alphabetic";f.textAlign="center";f.lineWidth=400;c.addChild(f);var q=s_oSpriteLibrary.getSprite("mod_easy_icon");h=new CGfxButton(n,530,q,s_oStage);h.addEventListener(ON_MOUSE_UP,this._selectEasy,this);g=new createjs.Text(TEXT_MEDIUM," 50px "+SECONDARY_FONT,PRIMARY_FONT_COLOUR);g.textBaseline="alphabetic";g.textAlign="center";g.lineWidth=400;d.addChild(g);q=s_oSpriteLibrary.getSprite("mod_medium_icon");k=new CGfxButton(n,980,q,s_oStage);k.addEventListener(ON_MOUSE_UP,
this._selectMedium,this);e=new createjs.Text(TEXT_HARD," 50px "+SECONDARY_FONT,PRIMARY_FONT_COLOUR);e.textBaseline="alphabetic";e.textAlign="center";e.lineWidth=400;b.addChild(e);q=s_oSpriteLibrary.getSprite("mod_hard_icon");l=new CGfxButton(n,1430,q,s_oStage);l.addEventListener(ON_MOUSE_UP,this._selectHard,this);s_oStage.addChild(c,d,b);p=new createjs.Shape;p.graphics.beginFill("black").drawRect(0,0,CANVAS_WIDTH,CANVAS_HEIGHT);s_oStage.addChild(p);createjs.Tween.get(p).to({alpha:0},400).call(function(){p.visible=
!1})};this._selectEasy=function(){r.unload();$(s_oMain).trigger("start_level",1);s_oMain.gotoGame(0)};this._selectMedium=function(){r.unload();$(s_oMain).trigger("start_level",1);s_oMain.gotoGame(1)};this._selectHard=function(){r.unload();$(s_oMain).trigger("start_level",1);s_oMain.gotoGame(2)};this.unload=function(){s_oStage.removeAllChildren();a=null};this._onAudioToggle=function(){createjs.Sound.setMute(s_bAudioActive);s_bAudioActive=!s_bAudioActive};var r=this;this._init()}
function CGame(a){function c(a){a||(a=window.event);a.preventDefault();a=a.keyCode-48;10>a&&0<a?t.pressNumButton(a):-2===a?t.pressDelButton():58>a&&48<a&&t.pressNumButton(a-48)}function d(a){a.preventDefault();a=a.keyCode-48;10>a&&0<a?t.releaseNumButton(a):-2===a?t.releaseDelButton():58>a&&48<a&&t.releaseNumButton(a-48)}var b,f,h,g,k,e,l,m,p,r,n,q,u,y,w,z,x,t,E=null,v,F,C,B,D;this._init=function(){m=l=e=k=g=h=!1;y=u=p=r=n=0;var a=createBitmap(s_oSpriteLibrary.getSprite("bg_game"));s_oStage.addChild(a);
C=null;t=new CInterface;v=new CGrid;w=Array(81);this._generateValidGrid(w);w=this._convertToMatrix(w);z=[];for(a=0;9>a;a++){z[a]=[];for(var b=0;9>b;b++)z[a][b]=w[a][b]}F=new CSudokuLoader;f=!0;!1===s_bMobile&&(document.onkeydown=c,document.onkeyup=d)};this.getHint=function(){u++;for(var a=[],b=0;9>b;b++)for(var c=0;9>c;c++)0===w[b][c]&&a.push({row:b,col:c});if(1===a.length)this.gameOver();else if(0!==a.length){shuffle(a);b=a[0].row;c=a[0].col;var e=z[b][c];w[b][c]=e;v.setHintNumber(b,c,e);v.setActiveCell(a[0]);
v.updateNote(e);v.setActiveCell(a[0]);this._getEndCounterAndSetButCounter()}};this.setNoTime=function(){b=!1;t.setNoTime();m=!0};this.solveAndWrite=function(){for(var a=0;9>a;a++)for(var b=0;9>b;b++)v.isGiven(a,b)&&w[a][b]===z[a][b]||(v.setSolvedNumber(a,b,z[a][b]),w[a][b]=z[a][b]);this._setEndingStateWhenSolve();l=!0};this.resetGame=function(){for(var a=0;9>a;a++)for(var b=0;9>b;b++)v.isGiven(a,b)||(v.deleteResetNumber(a,b),w[a][b]=0);this._getEndCounterAndSetButCounter();v.turnOffAllCells();v.highlightCells()};
this.fillWithNote=function(){this.clearNoteFill();for(var a=v.getList(0),b=0;b<a.length;b++)for(var c=a[b],f=1;10>f;f++)!0!==v.checkCollision(f,c.row,c.col,!1)&&v.writeHelpNote(f,c.row,c.col);e=!0};this.deleteAllNote=function(){this.clearNoteFill()};this.clearNoteFill=function(){v.deleteAllNote()};this.setNoteState=function(){h=!h};this.setDigitState=function(){k=!k;g=!1;p=0};this.setDeleteState=function(){g=!0;p=0};this.setCurNum=function(a){g=!1;p=a};this.activeCell=function(a){k&&!g?(v.setActiveCell(a),
this.writeNum(p)):k&&g?(v.setActiveCell(a),v.deleteCell()):v.setActiveCell(a)};this.writeNum=function(a){if(h)v.writeNote(a);else{var b=v.getCurActiveCell().row,c=v.getCurActiveCell().col,e=v.getCurActiveCell().num;v.writeNum(a);t.updateCounterOnButton(a,v.getList(a).length);0!==e&&t.updateCounterOnButton(e,v.getList(e).length);w[b][c]=a}};this.deleteCell=function(){var a=v.getCurActiveCell().num,b=v.getCurActiveCell().row,c=v.getCurActiveCell().col;v.deleteCell();0!==a&&(t.updateCounterOnButton(a,
v.getList(a).length),w[b][c]=0)};this.showPausePanel=function(a){a?null===C&&(C=new CPausePanel):null!==C&&(C.unload(),C=null)};this.tryShowAd=function(){y++;y===AD_SHOW_COUNTER&&(y=0,$(s_oMain).trigger("show_interlevel_ad"))};this.restartGame=function(){this.unload();this._init()};this.unload=function(){t.unload();null!==E&&E.unload();createjs.Tween.removeAllTweens();s_oStage.removeAllChildren();s_oGame=null};this.onExit=function(){this.unload();s_oMain.gotoMenu()};this._onExitHelp=function(){b=
!0};this.checkEndGame=function(a){"add"===a?r++:r--;81===r&&this.gameOver()};this.gameOver=function(){var a=Math.floor((TIME_BONUS_LIMIT[s_iDifficultyMode]-n)/100);E=CEndPanel(s_oSpriteLibrary.getSprite("msg_box"),e,l,m,u,a);E.show(n)};this.pauseTimer=function(a){b=!a};this.update=function(){if(f){F.update();for(var a=0;12>a;a++){for(var c=0;9>c;c++)for(var e=0;9>e;e++)w[c][e]=z[c][e];this._generateMask(s_iDifficultyMode);this._coverGrid(w);q=solve(w);if(1!==q){f=!1;F.unload();this._coverGrid(w);
this.setGrid(w);b=!0;s_oMain.startUpdate();break}}}b&&(n+=s_iTimeElaps,5999E3<n&&(n=5999E3),t.refreshTime(formatTime(n)))};this.setGrid=function(a){for(var b=0;9>b;b++)for(var c=0;9>c;c++)v.setGiven(b,c,a[b][c]);this._getEndCounterAndSetButCounter()};this._getEndCounterAndSetButCounter=function(){r=0;for(var a=1;10>a;a++){var b=v.getList(a).length;r+=b;t.updateCounterOnButton(a,b)}};this._setEndingStateWhenSolve=function(){r=81;for(var a=1;10>a;a++)t.updateCounterOnButton(a,9);B=new createjs.Shape;
B.graphics.beginFill("rgba(255,255,255,0.01)").drawRect(0,0,CANVAS_WIDTH,CANVAS_HEIGHT);s_oStage.addChild(B);D=B.on("mousedown",this.buttonDownWhenSolve);s_bMobile||(D=B.on("mouseover",this.buttonOverWhenSolve))};this.buttonDownWhenSolve=function(){B.off("mousedown",D);s_bMobile||B.off("mouseover",D);H.gameOver()};this.buttonOverWhenSolve=function(a){s_bMobile||(a.target.cursor="pointer")};this._convertToMatrix=function(a){for(var b=0,c=[],e=0;81>e;e+=9)c[b]=[a[e],a[e+1],a[e+2],a[e+3],a[e+4],a[e+
5],a[e+6],a[e+7],a[e+8]],b++;return c};this._generateMask=function(a){x=[];for(var b=0;9>b;b++){x[b]=[];for(var c=0;9>c;c++)x[b][c]=0}b=MAX_GIVENS_EASY-RANGE_GIVENS;switch(a){case EASY_MODE:b=MAX_GIVENS_EASY-RANGE_GIVENS;var e=b+Math.ceil(Math.random()*RANGE_GIVENS);var f=LOWER_BOUND_EASY;break;case MEDIUM_MODE:b=MAX_GIVENS_MEDIUM-RANGE_GIVENS;e=b+Math.ceil(Math.random()*RANGE_GIVENS);f=LOWER_BOUND_MEDIUM;break;case HARD_MODE:b=MAX_GIVENS_HARD-RANGE_GIVENS,e=b+Math.ceil(Math.random()*RANGE_GIVENS),
f=LOWER_BOUND_HARD}var d=[];for(b=0;9>b;b++)b<f?d.push(1):d.push(0);a=[];for(b=0;9>b;b++)for(a[b]=0,shuffle(d),c=0;9>c;c++)1===d[c]&&(x[b][c]=1);var l=[];for(b=0;9>b;b++)for(l[b]=0,shuffle(d),c=0;9>c;c++)1===d[c]&&(x[c][b]=1);for(b=d=0;9>b;b++)for(c=0;9>c;c++)1===x[b][c]&&(a[b]++,l[c]++,d++);e=d-e;if(0>e)this._generateMask(s_iDifficultyMode);else if(0===e)return;d=[];for(b=0;9>b;b++)for(c=0;9>c;c++)1===x[b][c]&&d.push({row:b,col:c,weightRow:a[b],weightCol:l[c],weightTotal:a[b]+l[c]});d.sort(function(a,
b){return a.weightTotal<b.weightTotal?-1:a.weightTotal>b.weightTotal?1:0});for(c=0;c<e;){b=d.length-1;if(0>b)break;if(d[b].weightRow>f&&d[b].weightCol>f){x[d[b].row][d[b].col]=0;var g=d[b].row,h=d[b].col;a[g]--;l[h]--;for(b=0;b<d.length;b++)d[b].row===g&&(d[b].weightRow=a[g],d[b].weightTotal--),d[b].col===h&&(d[b].weightCol=l[h],d[b].weightTotal--);c++}d.pop()}};this._coverGrid=function(a){for(var b=0;9>b;b++)for(var c=0;9>c;c++)0===x[b][c]&&(a[b][c]=0)};this.printGrid=function(a){for(var b="",c=
0;9>c;c++){for(var e=0;9>e;e++)if(b+=a[c][e]+" ",2===e||5===e)b+="| ";b+="\n";if(2===c||5===c)b+="---------------------\n"}trace(b)};this._generateValidGrid=function(a){for(var b=0;9>b;b++)for(var c=0;9>c;c++)a[9*b+c]=(3*b+Math.floor(b/3)+c)%9+1;for(b=0;42>b;b++){var e=Math.ceil(9*Math.random());do var d=Math.ceil(9*Math.random());while(e===d);for(c=0;9>c;c++)for(var f=0;9>f;f++)a[9*c+f]===e?a[9*c+f]=d:a[9*c+f]===d&&(a[9*c+f]=e)}for(f=0;42>f;f++)for(e=Math.floor(3*Math.random()),d=Math.floor(3*Math.random()),
c=0;9>c;c++)b=a[9*c+(3*e+f%3)],a[9*c+(3*e+f%3)]=a[9*c+(3*d+f%3)],a[9*c+(3*d+f%3)]=b;for(e=0;42>e;e++)for(f=Math.floor(3*Math.random()),d=Math.floor(3*Math.random()),c=0;9>c;c++)b=a[9*c+(e%3*3+f)],a[9*c+(e%3*3+f)]=a[9*c+(e%3*3+d)],a[9*c+(e%3*3+d)]=b;for(e=0;42>e;e++)for(c=Math.floor(3*Math.random()),d=Math.floor(3*Math.random()),f=0;9>f;f++)b=a[9*(e%3*3+c)+f],a[9*(e%3*3+c)+f]=a[9*(e%3*3+d)+f],a[9*(e%3*3+d)+f]=b};s_oGame=this;MAX_GIVENS_EASY=a.max_givens_beginner;MAX_GIVENS_MEDIUM=a.max_givens_intermediate;
MAX_GIVENS_HARD=a.max_givens_advanced;TIME_BONUS_LIMIT[0]=a.bonus_time_beginner;TIME_BONUS_LIMIT[1]=a.bonus_time_intermediate;TIME_BONUS_LIMIT[2]=a.bonus_time_advanced;AD_SHOW_COUNTER=a.ad_show_counter;var H=this;this._init()}var s_oGame;
function CInterface(){var a,c,d,b,f,h,g,k,e,l,m,p,r,n,q,u,y,w,z,x;this._init=function(){e=[];for(var t=0;9>t;t++)e[t+1]=5<t?new CNumButton(97+177.5*(t-6),1650,t+1):new CNumButton(97+177.5*t,1500,t+1);t=s_oSpriteLibrary.getSprite("but_del_toggle");l=new CDeleteButton(629.5,1650,t,!1);l.changeMode();t=s_oSpriteLibrary.getSprite("note_toggle");m=new CToggle(807,1650,t,!0,s_oStage);m.addEventListener(ON_MOUSE_UP,this._onNoteToggle,this);t=s_oSpriteLibrary.getSprite("mode_toggle");p=new CToggle(984.5,
1650,t,!0,s_oStage);p.addEventListener(ON_MOUSE_UP,this._onModeToggle,this);var x;t=s_oSpriteLibrary.getSprite("but_exit");g=CANVAS_WIDTH-t.height/2-20;k=t.height/2+10;z=new CGfxButton(g,k,t,s_oStage);z.addEventListener(ON_MOUSE_UP,this._onExit,this);f=x=CANVAS_WIDTH-t.width/2-175;h=t.height/2+10;if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)t=s_oSpriteLibrary.getSprite("audio_icon"),y=new CToggle(f,h,t,s_bAudioActive,s_oStage),y.addEventListener(ON_MOUSE_UP,this._onAudioToggle,this);x=CANVAS_WIDTH-
t.width/2-257;t=s_oSpriteLibrary.getSprite("config_icon");d=x;b=t.height/2+10;w=new CGfxButton(d,b,t,s_oStage);w.addEventListener(ON_MOUSE_UP,this._onConf,this);x=CANVAS_WIDTH-t.width/2-490;t=s_oSpriteLibrary.getSprite("but_help_icon");a=x;c=t.height/2+10;r=new CGfxButton(a,c,t,s_oStage);r.addEventListener(ON_MOUSE_UP,this._onHelpPress,this);t=s_oSpriteLibrary.getSprite("time_display");u=createBitmap(t);u.x=220;u.y=260;s_oStage.addChild(u);n=new createjs.Text(TEXT_TIME,"bold 60px "+PRIMARY_FONT,PRIMARY_FONT_COLOUR);
n.x=40;n.y=325;n.textAlign="left";n.textBaseline="alphabetic";n.lineWidth=200;s_oStage.addChild(n);q=new createjs.Text("00:00","bold 60px "+PRIMARY_FONT,"#ffffff");q.x=245;q.y=325;q.textAlign="left";q.textBaseline="alphabetic";q.lineWidth=200;s_oStage.addChild(q);this.refreshButtonPos(s_iOffsetX,s_iOffsetY)};this.unload=function(){if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)y.unload(),y=null;z.unload();for(var a=0;9>a;a++)e[a+1].unload();l.unload();m.unload();p.unload();r.unload();s_oInterface=x=
null};this.refreshButtonPos=function(e,l){z.setPosition(g-e,l+k);w.setPosition(d-e,l+b);r.setPosition(a-e,l+c);!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||y.setPosition(f-e,l+h)};this.refreshTime=function(a){q.text=a};this._onConf=function(){x=new CConfigPanel};this.setNoTime=function(){s_oStage.removeChild(n,q,u)};this._onHelpPress=function(){new CHelpPanel;s_oGame.pauseTimer(!0)};this._onNoteToggle=function(){s_oGame.setNoteState()};this._onModeToggle=function(){for(var a=0;9>a;a++)e[a+1].changeMode();
l.changeMode();this.setAllBlackColor();s_oGame.setDigitState()};this.updateCounterOnButton=function(a,b){e[a].clearCounter();e[a].setCounter(b)};this.pressNumButton=function(a){e[a].buttonDown()};this.releaseNumButton=function(a){e[a].buttonRelease()};this.pressDelButton=function(){l.buttonDown()};this.releaseDelButton=function(a){l.buttonRelease()};this.setAllBlackColor=function(){for(var a=0;9>a;a++)e[a+1].changeNumColor(!1);l.reset()};this.resetFullscreenBut=function(){x&&x.resetFullscreenBut()};
this.onExitFromConfig=function(){x=null};this._onAudioToggle=function(){Howler.mute(s_bAudioActive);s_bAudioActive=!s_bAudioActive};this._onExit=function(){new CAreYouSurePanel(s_oInterface._onConfirmExit)};this._onNegateExit=function(){};this._onConfirmExit=function(){$(s_oMain).trigger("end_level",1);$(s_oMain).trigger("end_session");$(s_oMain).trigger("show_interlevel_ad");s_oGame.onExit()};s_oInterface=this;this._init();return this}var s_oInterface=null;
function CHelpPanel(){var a,c,d,b,f,h,g,k,e,l,m,p,r,n,q,u,y,w;this._init=function(){var x=this;e=createBitmap(s_oSpriteLibrary.getSprite("bg_help"));var t=CANVAS_WIDTH/2,z=CANVAS_HEIGHT/2-400;a=new createjs.Text(TEXT_HELP0," 140px "+SECONDARY_FONT,PRIMARY_FONT_COLOUR);a.x=t;a.y=z-100;a.textAlign="center";a.textBaseline="alphabetic";a.lineWidth=700;c=new createjs.Text(TEXT_HELP1," 50px "+PRIMARY_FONT,PRIMARY_FONT_COLOUR);c.x=t;c.y=z;c.textAlign="center";c.textBaseline="alphabetic";c.lineWidth=950;
m=new createjs.Container;m.addChild(e,a,c);s_oStage.addChild(m);r=m.on("pressup",function(){x._onExitHelp()});l=createBitmap(s_oSpriteLibrary.getSprite("bg_help2"));d=!1===s_bMobile?TEXT_HELP1_PAGE2:TEXT_HELP1_MOB_PAGE2;b=new createjs.Text(TEXT_HELP0_PAGE2," 140px "+SECONDARY_FONT,PRIMARY_FONT_COLOUR);b.x=.5*CANVAS_WIDTH;b.y=z-100;b.textAlign="center";b.textBaseline="alphabetic";b.lineWidth=800;f=new createjs.Text(d," 35px "+PRIMARY_FONT,PRIMARY_FONT_COLOUR);f.x=CANVAS_WIDTH/2;f.y=CANVAS_HEIGHT/2-
432;f.textAlign="center";f.lineWidth=900;f.textBaseline="alphabetic";h=new createjs.Text(TEXT_HELP2_PAGE2," 35px "+PRIMARY_FONT,PRIMARY_FONT_COLOUR);h.x=CANVAS_WIDTH/2-180;h.y=CANVAS_HEIGHT/2-272;h.textAlign="left";h.lineWidth=600;h.textBaseline="alphabetic";g=new createjs.Text(TEXT_HELP3_PAGE2," 35px "+PRIMARY_FONT,PRIMARY_FONT_COLOUR);g.x=CANVAS_WIDTH/2-380;g.y=CANVAS_HEIGHT/2+45;g.textAlign="left";g.lineWidth=600;g.textBaseline="alphabetic";k=new createjs.Text(TEXT_HELP4_PAGE2," 35px "+PRIMARY_FONT,
PRIMARY_FONT_COLOUR);k.x=CANVAS_WIDTH/2-180;k.y=CANVAS_HEIGHT/2+340;k.textAlign="left";k.lineWidth=600;k.textBaseline="alphabetic";p=new createjs.Container;p.addChild(l,b,f,h,g,k);p.visible=0;s_oStage.addChild(p);n=p.on("pressup",function(){x._onExitHelp()});createjs.Tween.get(p).to({alpha:1},700);y=createBitmap(s_oSpriteLibrary.getSprite("arrow"));y.x=740;y.y=1450;y.alpha=0;q=y.on("click",x._changePageTo2);if(!s_bMobile)y.on("mouseover",x.buttonOver);s_oStage.addChild(y);w=createBitmap(s_oSpriteLibrary.getSprite("arrow"));
w.scaleX=-1;w.x=340;w.y=1450;w.visible=!1;u=w.on("click",x._changePageTo1);if(!s_bMobile)w.on("mouseover",x.buttonOver);s_oStage.addChild(w);createjs.Tween.get(y).to({alpha:1},700)};this.unload=function(){s_oStage.removeChild(m,p,y,w);m.off("pressup",r);p.off("pressup",n);s_bMobile||(y.off("mouseover",q),w.off("mouseover",u))};this._changePageTo1=function(){p.visible=!1;w.visible=!1;m.visible=!0;y.visible=!0};this._changePageTo2=function(){m.visible=!1;y.visible=!1;p.visible=!0;w.visible=!0};this.buttonOver=
function(a){s_bMobile||(a.target.cursor="pointer")};this._onExitHelp=function(){$(s_oMain).trigger("show_interlevel_ad");z.unload();s_oGame._onExitHelp()};var z=this;this._init()}
function CPausePanel(){var a,c,d;this._init=function(){a=createBitmap(s_oSpriteLibrary.getSprite("msg_box"));d=new createjs.Text(TEXT_PAUSE," 120px "+SECONDARY_FONT,PRIMARY_FONT_COLOUR);d.x=CANVAS_WIDTH/2;d.y=CANVAS_HEIGHT/2;d.textAlign="center";d.textBaseline="alphabetic";d.lineWidth=700;c=new createjs.Container;c.addChild(a,d);s_oStage.addChild(c);s_oStage.update()};this.unload=function(){s_oStage.removeChild(c)};this._init()}
function CSudokuLoader(){var a,c,d,b,f,h;this._init=function(){a=!0;c=0;d=new createjs.Container;var g=(new createjs.Graphics).beginFill("rgba(0,0,0,0.8)").drawRect(0,0,CANVAS_WIDTH,CANVAS_HEIGHT);h=new createjs.Shape(g);h.on("click",function(){});b=new createjs.Text(TEXT_GENERATE_SUDOKU," 60px "+PRIMARY_FONT,"#ffffff");b.x=.5*CANVAS_WIDTH;b.y=.5*CANVAS_HEIGHT-100;b.textAlign="center";b.textBaseline="alphabetic";b.lineWidth=800;f=new createjs.Text(""," 180px "+PRIMARY_FONT,"#ffffff");f.x=.5*CANVAS_WIDTH-
76;f.y=.5*CANVAS_HEIGHT+50;f.textAlign="left";f.textBaseline="alphabetic";f.lineWidth=800;d.addChild(h,b,f);s_oStage.addChild(d)};this.unload=function(){a=!1;s_oStage.removeChild(d)};this.update=function(){a&&(c+=s_iTimeElaps,0<=c&&c<TIME_LOOP_WAIT/4?f.text="":c>=TIME_LOOP_WAIT/4&&c<2*TIME_LOOP_WAIT/4?f.text=".":c>=2*TIME_LOOP_WAIT/4&&c<3*TIME_LOOP_WAIT/4?f.text="..":c>=3*TIME_LOOP_WAIT/4&&c<TIME_LOOP_WAIT?f.text="...":c=0)};s_oSudokuLoader=this;this._init()}var s_oSudokuLoader;
function CEndPanel(a,c,d,b,f,h){var g,k,e,l,m,p,r,n,q;this._init=function(a,b,c,f,d,h){g=h;if(0<d){var u=Math.floor(TIME_BONUS_LIMIT[s_iDifficultyMode]/4E3);g-=u*d}b&&(g/=2);if(c||f)g=0;0>g&&(g=0);k=[];b&&k.push(TEXT_HELP_NOTE+" "+TEXT_INFO_NOTE);c&&k.push(TEXT_HELP_SOLVE+" "+TEXT_INFO_SOLVE);f&&k.push(TEXT_HELP_TIME+" "+TEXT_INFO_SOLVE);0<d&&(1<d?k.push(d+TEXT_HELP_HINTS+" (-"+u+" "+TEXT_INFO_HINT):k.push(d+TEXT_HELP_HINT+" (-"+u+" "+TEXT_INFO_HINT));l=createBitmap(a);l.x=0;l.y=0;p=new createjs.Text("",
" 80px "+SECONDARY_FONT,PRIMARY_FONT_COLOUR);p.x=CANVAS_WIDTH/2;p.y=CANVAS_HEIGHT/2-462;p.textAlign="center";p.textBaseline="alphabetic";p.lineWidth=700;r=new createjs.Text("","bold 40px "+PRIMARY_FONT,PRIMARY_FONT_COLOUR);r.x=CANVAS_WIDTH/2;r.y=CANVAS_HEIGHT/2-160;r.textAlign="center";r.textBaseline="alphabetic";r.lineWidth=900;e=[];e[0]=new createjs.Text("","bold 40px "+PRIMARY_FONT,PRIMARY_FONT_COLOUR);e[0].x=280;e[0].y=CANVAS_HEIGHT/2-90;e[0].textAlign="left";e[0].textBaseline="alphabetic";e[0].lineWidth=
600;e[1]=new createjs.Text("","bold 40px "+PRIMARY_FONT,PRIMARY_FONT_COLOUR);e[1].x=280;e[1].y=CANVAS_HEIGHT/2+10;e[1].textAlign="left";e[1].textBaseline="alphabetic";e[1].lineWidth=600;e[2]=new createjs.Text("","bold 40px "+PRIMARY_FONT,PRIMARY_FONT_COLOUR);e[2].x=280;e[2].y=CANVAS_HEIGHT/2+110;e[2].textAlign="left";e[2].textBaseline="alphabetic";e[2].lineWidth=660;e[3]=new createjs.Text("","bold 40px "+PRIMARY_FONT,PRIMARY_FONT_COLOUR);e[3].x=280;e[3].y=CANVAS_HEIGHT/2+210;e[3].textAlign="left";
e[3].textBaseline="alphabetic";e[3].lineWidth=600;n=new createjs.Text(""," 70px "+SECONDARY_FONT,PRIMARY_FONT_COLOUR);n.x=CANVAS_WIDTH/2;n.y=CANVAS_HEIGHT/2+380;n.textAlign="center";n.textBaseline="alphabetic";n.lineWidth=700;m=new createjs.Container;m.alpha=0;m.visible=!1;m.addChild(l,r,p,e[0],e[1],e[2],e[3],n);s_oStage.addChild(m)};this.unload=function(){m.off("mousedown",q)};this._initListener=function(){q=m.on("mousedown",this._onExit)};this.show=function(a){playSound("game_over",1,!1);a=formatTime(a);
var l=[];l[0]=TEXT_EASY;l[1]=TEXT_MEDIUM;l[2]=TEXT_EASY;p.text=b?TEXT_GAMEOVER+l[s_iDifficultyMode]+TEXT_SUDOKU:TEXT_GAMEOVER+l[s_iDifficultyMode]+TEXT_SUDOKU+TEXT_IN+a;1===k.length?r.text=TEXT_HELP_USED:1<k.length&&(r.text=TEXT_HELPS_USED);if(0<k.length)for(l=0;l<k.length;l++)e[l].text="-"+k[l];n.text=TEXT_SCORE+" "+g;m.visible=!0;var u=this;createjs.Tween.get(m).to({alpha:1},500).call(function(){u._initListener()});$(s_oMain).trigger("save_score",[g,s_iDifficultyMode,a,c,d,b,f]);$(s_oMain).trigger("share_event",
h);$(s_oMain).trigger("end_level",1)};this._onExit=function(){m.off("mousedown",q);s_oStage.removeChild(m);$(s_oMain).trigger("end_session");s_oGame.onExit()};this._init(a,c,d,b,f,h);return this}
function CConfigPanel(){var a=null,c=null,d,b,f,h,g,k,e,l,m,p,r,n,q,u,y,w,z,x,t,E,v,F,C,B;this._init=function(){s_oGame.pauseTimer(!0);var D=this;l=createBitmap(s_oSpriteLibrary.getSprite("msg_box"));x=new createjs.Container;x.x=130;x.y=430;s_oStage.addChild(x);d=new createjs.Text(TEXT_GETHINT," 50px "+SECONDARY_FONT,PRIMARY_FONT_COLOUR);d.textAlign="left";d.textBaseline="alphabetic";d.lineWidth=700;x.addChild(d);var A=s_oSpriteLibrary.getSprite("but_help_hint");y=new CGfxButton(750,0,A,x);y.addEventListener(ON_MOUSE_UP,
this._onHintPress,this);t=new createjs.Container;t.x=130;t.y=600;s_oStage.addChild(t);b=new createjs.Text(TEXT_FILL_WITH_NOTE," 50px "+SECONDARY_FONT,PRIMARY_FONT_COLOUR);b.textAlign="left";b.textBaseline="alphabetic";b.lineWidth=700;t.addChild(b);A=s_oSpriteLibrary.getSprite("but_help_note");p=new CGfxButton(750,0,A,t);p.addEventListener(ON_MOUSE_UP,this._onHelpPress,this);E=new createjs.Container;E.x=130;E.y=770;s_oStage.addChild(E);f=new createjs.Text(TEXT_SOLVE," 50px "+SECONDARY_FONT,PRIMARY_FONT_COLOUR);
f.textAlign="left";f.textBaseline="alphabetic";f.lineWidth=700;E.addChild(f);A=s_oSpriteLibrary.getSprite("but_solve");n=new CGfxButton(750,0,A,E);n.addEventListener(ON_MOUSE_UP,this._onSolvePress,this);v=new createjs.Container;v.x=130;v.y=1210;s_oStage.addChild(v);h=new createjs.Text(TEXT_RESET," 50px "+SECONDARY_FONT,PRIMARY_FONT_COLOUR);h.textAlign="left";h.textBaseline="alphabetic";h.lineWidth=700;v.addChild(h);A=s_oSpriteLibrary.getSprite("but_reset");q=new CGfxButton(750,0,A,v);q.addEventListener(ON_MOUSE_UP,
this._onResetPress,this);F=new createjs.Container;F.x=130;F.y=1390;s_oStage.addChild(F);g=new createjs.Text(TEXT_DELETE_ALL_NOTE," 50px "+SECONDARY_FONT,PRIMARY_FONT_COLOUR);g.textAlign="left";g.textBaseline="alphabetic";g.lineWidth=700;F.addChild(g);A=s_oSpriteLibrary.getSprite("but_del_note");r=new CGfxButton(750,0,A,F);r.addEventListener(ON_MOUSE_UP,this._onDelPress,this);C=new createjs.Container;C.x=130;C.y=1570;s_oStage.addChild(C);k=new createjs.Text(TEXT_SETNOTIME," 50px "+SECONDARY_FONT,PRIMARY_FONT_COLOUR);
k.textAlign="left";k.textBaseline="alphabetic";k.lineWidth=700;C.addChild(k);A=s_oSpriteLibrary.getSprite("but_time");u=new CGfxButton(750,0,A,C);u.addEventListener(ON_MOUSE_UP,this._onTimePress,this);A=window.document;var G=A.documentElement;a=G.requestFullscreen||G.mozRequestFullScreen||G.webkitRequestFullScreen||G.msRequestFullscreen;c=A.exitFullscreen||A.mozCancelFullScreen||A.webkitExitFullscreen||A.msExitFullscreen;!1===ENABLE_FULLSCREEN&&(a=!1);B=new createjs.Container;B.x=130;B.y=1030;s_oStage.addChild(B);
a&&screenfull.enabled&&(e=new createjs.Text(TEXT_FULLSCREEN," 50px "+SECONDARY_FONT,PRIMARY_FONT_COLOUR),e.textAlign="left",e.textBaseline="alphabetic",e.lineWidth=700,B.addChild(e),A=s_oSpriteLibrary.getSprite("but_fullscreen"),w=new CToggle(750,0,A,s_bFullscreen,B),w.addEventListener(ON_MOUSE_UP,this._onFullscreenRelease,this));m=new createjs.Container;m.addChild(l,x,t,E,v,F,C,B);s_oStage.addChild(m);z=l.on("pressup",function(){D._onExitHelp()})};this.unload=function(){$(s_oMain).trigger("show_interlevel_ad");
s_oStage.removeChild(m);l.off("pressup",z);s_oInterface.onExitFromConfig()};this._onHelpPress=function(){s_oGame.fillWithNote();D._onExitHelp()};this._onDelPress=function(){s_oGame.deleteAllNote();D._onExitHelp()};this._onSolvePress=function(){s_oGame.solveAndWrite();D.unload()};this._onResetPress=function(){$(s_oMain).trigger("restart_level",1);s_oGame.resetGame();D._onExitHelp()};this._onTimePress=function(){s_oGame.setNoTime();D._onExitHelp()};this._onHintPress=function(){s_oGame.getHint();D._onExitHelp()};
this.resetFullscreenBut=function(){a&&screenfull.enabled&&w.setActive(s_bFullscreen)};this._onFullscreenRelease=function(){s_bFullscreen?c.call(window.document):a.call(window.document.documentElement);sizeHandler()};this._onExitHelp=function(){D.unload();s_oGame.pauseTimer(!1)};var D=this;this._init()}
function CGrid(){var a,c,d,b,f,h,g,k;this._init=function(){c=a=0;h=new createjs.Container;h.x=CANVAS_WIDTH/2;h.y=880;s_oStage.addChild(h);var e=CELL_SIZE,l=9*CELL_SIZE+44,m=.5*l,p=e,r=[];r.push(.5*e);g=[];for(var n=0;8>n;n++){if(2===n%3){var q=(new createjs.Graphics).beginFill("rgba(0,0,0,1)").drawRect(-m,-m+p,l,10);p+=e+10}else q=(new createjs.Graphics).beginFill("rgba(0,0,0,1)").drawRect(-m,-m+p,l,4),p+=e+4;r.push(p-.5*e);g[n]=new createjs.Shape(q);h.addChild(g[n])}p=e;k=[];for(n=0;8>n;n++)2===
n%3?(q=(new createjs.Graphics).beginFill("rgba(0,0,0,1)").drawRect(-m+p,-m,10,l),p+=e+10):(q=(new createjs.Graphics).beginFill("rgba(0,0,0,1)").drawRect(-m+p,-m,4,l),p+=e+4),k[n]=new createjs.Shape(q),h.addChild(k[n]);q=(new createjs.Graphics).beginFill("rgba(0,0,0,1)").drawRect(-m-10,-m-10,10,l+20);n=new createjs.Shape(q);h.addChild(n);q=(new createjs.Graphics).beginFill("rgba(0,0,0,1)").drawRect(m,-m-10,10,l+20);n=new createjs.Shape(q);h.addChild(n);q=(new createjs.Graphics).beginFill("rgba(0,0,0,1)").drawRect(-m-
10,-m-10,l+20,10);n=new createjs.Shape(q);h.addChild(n);q=(new createjs.Graphics).beginFill("rgba(0,0,0,1)").drawRect(-m-10,+m,l+20,10);l=new createjs.Shape(q);h.addChild(l);d=[];for(n=0;9>n;n++)for(d[n]=[],l=0;9>l;l++)d[n][l]={x:r[n],y:r[l]};b=[];for(n=0;9>n;n++)for(b[n]=[],l=0;9>l;l++)b[n][l]=new CCell(d[n][l].x-m,d[n][l].y-m,{row:n,col:l},h);f=[];for(n=0;10>n;n++)f[n]=[]};this.setCurNum=function(a){};this.setActiveCell=function(e){this.turnOffAllCells();a=e.row;c=e.col;this.highlightCells();0!==
b[a][c].getNumber()&&this.showSameNumbers(b[a][c].getNumber())};this.showCorner=function(){b[a][c].setCorner(!0)};this.turnOffAllCells=function(){for(var e=0;9>e;e++)for(var d=0;9>d;d++)b[e][d].highlight("off");b[a][c].setCorner(!1)};this.showSameNumbers=function(a){if(0!==a){for(var c=0;c<f[a].length;c++)b[f[a][c].row][f[a][c].col].highlight("green");for(c=0;9>c;c++)for(var e=0;9>e;e++)0!==b[c][e].getNote(a)&&b[c][e].highlight("green")}};this.highlightCells=function(){this.showCorner();for(var e=
0;9>e;e++)b[a][e].highlight("yellow");for(e=0;9>e;e++)b[e][c].highlight("yellow");e=3*Math.floor(a/3);for(var d=3*Math.floor(c/3),f=0;3>f;f++)for(var h=0;3>h;h++)b[e+f][d+h].highlight("yellow")};this.deleteCell=function(){b[a][c].getGiven()||(0!==b[a][c].getNumber()&&s_oGame.checkEndGame("remove"),this.deleteSmartFromList(b[a][c].getNumber()),b[a][c].clearCell(),this.turnOffAllCells(),this.highlightCells())};this.writeNum=function(e){b[a][c].getGiven()||0===e||e===b[a][c].getNumber()||(this.turnOffAllCells(),
this.highlightCells(),this.checkCollision(e,a,c,!0)||(0!==b[a][c].getNumber()&&this.deleteCell(),b[a][c].setNumber(e),this.insertSmartInList(e),this.updateNote(e),this.showSameNumbers(e),s_oGame.checkEndGame("add")))};this.deleteAllNote=function(){for(var e=0;e<f[0].length;e++)b[f[0][e].row][f[0][e].col].clearAllNote();this.turnOffAllCells();this.highlightCells();this.showSameNumbers(b[a][c].getNumber())};this.writeNote=function(e){b[a][c].getGiven()||(this.turnOffAllCells(),this.highlightCells(),
b[a][c].setNote(e),this.showSameNumbers(b[a][c].getNumber()))};this.writeHelpNote=function(a,c,d){b[c][d].setHelpNote(a)};this.setGiven=function(a,c,d){b[a][c].setGiven(d);f[d].push({row:a,col:c})};this.isGiven=function(a,c){return b[a][c].getGiven()};this.setSolvedNumber=function(a,c,d){b[a][c].setHintNumber(d);f[d].push({row:a,col:c});for(d=0;d<f[0].length;d++)f[0][d].row===a&&f[0][d].col===c&&f[0].splice(d,1)};this.setHintNumber=function(a,c,d){b[a][c].setHintNumber(d);f[d].push({row:a,col:c});
for(d=0;d<f[0].length;d++)f[0][d].row===a&&f[0][d].col===c&&f[0].splice(d,1)};this.deleteResetNumber=function(a,c){var d=b[a][c].getNumber();if(0!==d){for(var e=0;e<f[d].length;e++)f[d][e].row===a&&f[d][e].col===c&&f[d].splice(e,1);b[a][c].clearCell()}f[0].push({row:a,col:c})};this.updateNote=function(d){for(var e=0;9>e;e++)0!==b[a][e].getNote(d)&&b[a][e].clearNote(d),0!==b[e][c].getNote(d)&&b[e][c].clearNote(d);var f=3*Math.floor(a/3),h=3*Math.floor(c/3);for(e=0;3>e;e++)for(var g=0;3>g;g++)0!==b[f+
e][h+g].getNote(d)&&b[f+e][h+g].clearNote(d)};this.checkCollision=function(a,c,d,h){for(var e=3*Math.floor(c/3),g=3*Math.floor(d/3),k=0;k<f[a].length;k++)if(f[a][k].row===c||f[a][k].col===d||e<=f[a][k].row&&f[a][k].row<e+3&&g<=f[a][k].col&&f[a][k].col<g+3)return h&&b[f[a][k].row][f[a][k].col].highlight("red"),!0};this.deleteSmartFromList=function(b){if(0!==b){for(var d=0;d<f[b].length;d++)f[b][d].row===a&&f[b][d].col===c&&f[b].splice(d,1);f[0].push({row:a,col:c})}};this.insertSmartInList=function(b){if(0!==
b)for(f[b].push({row:a,col:c}),b=0;b<f[0].length;b++)f[0][b].row===a&&f[0][b].col===c&&f[0].splice(b,1)};this.removeList=function(a){f[a]={}};this.getList=function(a){return f[a]};this.viewList=function(a){trace(f[a]);trace(f[a].length)};this.getCurActiveCell=function(){return{row:a,col:c,num:b[a][c].getNumber()}};this.getCurGrid=function(){for(var a=[],c=0;9>c;c++){a[c]=[];for(var d=0;9>d;d++)a[c][d]=b[c][d].getNumber()}return a};this._init()}
function CCell(a,c,d,b){var f,h,g,k,e,l,m,p,r,n;this._init=function(a,b,c,d){f=!1;var u=CELL_SIZE;h=0;k=[];n=new createjs.Container;n.x=a;n.y=b;d.addChild(n);e={row:c.row,col:c.col};a=s_oSpriteLibrary.getSprite("background");b={images:[a],frames:{width:a.width/2,height:a.height,regX:a.width/2/2,regY:a.height/2},animations:{white:[0],grey:[1]}};b=new createjs.SpriteSheet(b);m=createSprite(b,"white",a.width/2/2,a.height/2,a.width/2,a.height);n.addChild(m);a=s_oSpriteLibrary.getSprite("highlight");b=
{images:[a],frames:{width:a.width/3,height:a.height,regX:a.width/3/2,regY:a.height/2},animations:{yellow:[0],green:[1],red:[2]}};b=new createjs.SpriteSheet(b);l=createSprite(b,"yellow",a.width/3/2,a.height/2,a.width/2,a.height);l.alpha=.9;l.visible=!1;n.addChild(l);g=[];a=u/3;g[1]={x:-a,y:-a};g[2]={x:0,y:-a};g[3]={x:a,y:-a};g[4]={x:-a,y:0};g[5]={x:0,y:0};g[6]={x:a,y:0};g[7]={x:-a,y:a};g[8]={x:0,y:a};g[9]={x:+a,y:a};this.clearAllNote();a=s_oSpriteLibrary.getSprite("cell_selected");p=createBitmap(a);
p.regX=a.width/2;p.regY=a.height/2;p.visible=!1;n.addChild(p);(new createjs.Graphics).beginFill("rgba(158,158,158,0.01)").drawRect(-u/2,-u/2,u,u);n.on("click",this._setActive)};this.unload=function(){b.removeChild(n)};this.setGiven=function(a){0!==a&&(m.gotoAndStop("grey"),f=!0);this.setNumber(a)};this.getGiven=function(){return f};this.setHintNumber=function(a){0!==a&&(this.clearNumber(),this.clearAllNote(),r=new createjs.Text(a,"bold 80px "+PRIMARY_FONT,"#add8fd"),r.textAlign="center",r.textBaseline=
"middle",n.addChild(r),h=a)};this.setNumber=function(a){0!==a&&(this.clearNumber(),this.clearAllNote(),r=new createjs.Text(a,"bold 80px "+PRIMARY_FONT,"#000000"),r.textAlign="center",r.textBaseline="middle",n.addChild(r),h=a)};this.getNumber=function(){return h};this.clearNumber=function(){h=0;n.removeChild(r)};this.setNote=function(a){0===h&&(0!==k[a]?this.clearNote(a):(k[a]=new createjs.Text(a," 30px "+PRIMARY_FONT,"#000000"),k[a].textAlign="center",k[a].textBaseline="middle",k[a].x=g[a].x,k[a].y=
g[a].y,n.addChild(k[a])))};this.setHelpNote=function(a){this.clearNote(a);k[a]=new createjs.Text(a," 30px "+PRIMARY_FONT,"#000000");k[a].textAlign="center";k[a].textBaseline="middle";k[a].x=g[a].x;k[a].y=g[a].y;n.addChild(k[a])};this.getNote=function(a){return k[a]};this.clearNote=function(a){n.removeChild(k[a]);k[a]=0};this.clearAllNote=function(){for(var a=1;10>a;a++)n.removeChild(k[a]),k[a]=0};this.clearCell=function(){this.clearNumber();this.clearAllNote()};this.highlight=function(a){l.visible=
!0;"off"!==a?l.gotoAndStop(a):l.visible=!1};this.setCorner=function(a){p.visible=a?!0:!1};this._setActive=function(){q.highlight("yellow");s_oGame.activeCell(e)};var q=this;this._init(a,c,d,b)}
function CNumButton(a,c,d){var b,f,h,g,k,e,l,m,p,r,n;this._init=function(a,c,d){h=!1;g=d;l=new createjs.Container;l.x=a;l.y=c;s_oStage.addChild(l);c=s_oSpriteLibrary.getSprite("but_num");k=createBitmap(c);a=c.width;c=c.height;k.regX=a/2;k.regY=c/2;e=new createjs.Text(d,"Bold 90px "+PRIMARY_FONT,"#000000");e.textAlign="center";e.textBaseline="middle";l.addChild(k,e);b=a/3-2;f=-c/3+5;this.setCounter(0);this._initListener()};this.unload=function(){l.off("mousedown",p);l.off("pressup",r);s_bMobile||l.off("mouseover",
n);s_oStage.removeChild(l)};this._initListener=function(){p=l.on("mousedown",this.buttonDown);r=l.on("pressup",this.buttonRelease);s_bMobile||(n=l.on("mouseover",this.buttonOver))};this.buttonRelease=function(){l.scaleX=1;l.scaleY=1;s_oGame.tryShowAd();h?(s_oGame.setCurNum(g),s_oInterface.setAllBlackColor(),q.changeNumColor(!0)):s_oGame.writeNum(g)};this.buttonDown=function(){l.scaleX=.9;l.scaleY=.9};this.buttonOver=function(a){s_bMobile||(a.target.cursor="pointer")};this.changeNumColor=function(a){e.color=
a?"#ff8814":"#000000"};this.changeMode=function(){h=!h};this.setCounter=function(a){m=new createjs.Text(a," 30px "+PRIMARY_FONT,"#000000");m.textAlign="center";m.textBaseline="middle";m.x=b;m.y=f;l.addChild(m)};this.clearCounter=function(){l.removeChild(m)};var q=this;this._init(a,c,d)}
function CCreditsPanel(){var a,c,d,b,f;this._init=function(){b=new createjs.Shape;b.graphics.beginFill("#0f0f0f").drawRect(0,0,CANVAS_WIDTH,CANVAS_HEIGHT);b.alpha=.01;f=b.on("click",this._onLogoButRelease);s_oStage.addChild(b);a=new createjs.Container;s_oStage.addChild(a);var h=s_oSpriteLibrary.getSprite("credit_bg"),g=createBitmap(h);g.regX=h.width/2;g.regY=h.height/2;a.addChild(g);a.x=CANVAS_WIDTH/2;a.y=CANVAS_HEIGHT/2;h=new createjs.Text(TEXT_DEVELOPED," 80px "+SECONDARY_FONT,"#000000");h.y=-120;
h.textAlign="center";h.textBaseline="middle";h.lineWidth=600;h.outline=5;g=new createjs.Text(TEXT_DEVELOPED," 80px "+SECONDARY_FONT,PRIMARY_FONT_COLOUR);g.y=h.y;g.textAlign="center";g.textBaseline="middle";g.lineWidth=600;a.addChild(g);h=new createjs.Text("www.codethislab.com"," 80px "+SECONDARY_FONT,PRIMARY_FONT_COLOUR);h.y=120;h.textAlign="center";h.textBaseline="middle";h.lineWidth=600;h.outline=5;g=new createjs.Text("www.codethislab.com"," 80px "+SECONDARY_FONT,PRIMARY_FONT_COLOUR);g.y=h.y;g.textAlign=
"center";g.textBaseline="middle";g.lineWidth=600;a.addChild(g);h=s_oSpriteLibrary.getSprite("ctl_logo");d=createBitmap(h);d.regX=h.width/2;d.regY=h.height/2;a.addChild(d);h=s_oSpriteLibrary.getSprite("but_exit");c=new CGfxButton(400,-204,h,a);c.addEventListener(ON_MOUSE_UP,this.unload,this)};this.unload=function(){s_oStage.removeChild(void 0);s_oStage.removeChild(a);c.unload();b.off("click",f)};this._onLogoButRelease=function(){window.open("http://www.codethislab.com/index.php?&l=en")};this._init()}
function CAreYouSurePanel(a,c){var d,b,f,h;this._init=function(a,c){f=new createjs.Container;h=f.on("mousedown",function(){});s_oStage.addChild(f);var e=s_oSpriteLibrary.getSprite("credit_bg"),g=createBitmap(e);g.regX=e.width/2;g.regY=e.height/2;f.addChild(g);f.x=CANVAS_WIDTH/2;f.y=CANVAS_HEIGHT/2;e=new createjs.Text(TEXT_ARE_SURE," 120px "+SECONDARY_FONT,PRIMARY_FONT_COLOUR);e.y=-100;e.textAlign="center";e.textBaseline="middle";e.lineWidth=800;f.addChild(e);d=new CGfxButton(150,150,s_oSpriteLibrary.getSprite("but_yes"),
f);d.addEventListener(ON_MOUSE_UP,this._onButYes,this);b=new CGfxButton(-150,150,s_oSpriteLibrary.getSprite("but_exit"),f);b.addEventListener(ON_MOUSE_UP,this._onButNo,this);b.pulseAnimation()};this._onButYes=function(){g.unload();a&&a()};this._onButNo=function(){g.unload();c&&c()};this.unload=function(){b.unload();d.unload();f.off("mousedown",h);s_oStage.removeChild(f)};var g=this;this._init(a,c)}
function extractHostname(a){a=-1<a.indexOf("://")?a.split("/")[2]:a.split("/")[0];a=a.split(":")[0];return a=a.split("?")[0]}function extractRootDomain(a){a=extractHostname(a);var c=a.split("."),d=c.length;2<d&&(a=c[d-2]+"."+c[d-1]);return a}
var getClosestTop=function(){var a=window,c=!1;try{for(;a.parent.document!==a.document;)if(a.parent.document)a=a.parent;else{c=!0;break}}catch(d){c=!0}return{topFrame:a,err:c}},getBestPageUrl=function(a){var c=a.topFrame,d="";if(a.err)try{try{d=window.top.location.href}catch(f){var b=window.location.ancestorOrigins;d=b[b.length-1]}}catch(f){d=c.document.referrer}else d=c.location.href;return d},TOPFRAMEOBJ=getClosestTop(),PAGE_URL=getBestPageUrl(TOPFRAMEOBJ);
function seekAndDestroy(){for(var a=extractRootDomain(PAGE_URL),c=[String.fromCharCode(99,111,100,101,116,104,105,115,108,97,98,46,99,111,109),String.fromCharCode(101,110,118,97,116,111,46,99,111,109),String.fromCharCode(99,111,100,101,99,97,110,121,111,110,46,99,111,109),String.fromCharCode(99,111,100,101,99,97,110,121,111,110,46,110,101,116)],d=0;d<c.length;d++)if(c[d]===a)return!0;return!1};